test: &default

  # Credentials for REST APIs
  client_id: AY9LJbVHcCPqRNiFPtPtTTkWVZFTdPhBAL66XPhFQjzoJcaVlCUekyPJc73l-vgL93EsLm9gCeTGyZFV
  client_secret: EBbFy5HGH-MGd5QjErI4PEpCfyR7XwPTGeUl8jH3NZELDd2bCWpvzi3FzjC3gpJ8Fr7aO1nAyblZlLDr

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: vendedor@facil.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
